"""mvp schema

Revision ID: fd3454a8c133
Revises: 
Create Date: 2025-08-22 13:47:10.965609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd3454a8c133'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=False),
    sa.Column('router_id', sa.String(length=17), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempts_left', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('router_id', sa.String(length=17), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=False),
    sa.Column('ttl_sec', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.create_index('ix_commands_router_created', ['router_id', 'created_at'], unique=False)

    op.create_table('devices',
    sa.Column('mac', sa.String(length=17), nullable=False),
    sa.Column('router_id', sa.String(length=17), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('mac')
    )
    op.create_table('routers',
    sa.Column('id', sa.String(length=17), nullable=False),
    sa.Column('router_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=False),
    sa.Column('router_id', sa.String(length=17), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ttl_sec', sa.Integer(), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_mac_status', ['mac', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_mac_status')

    op.drop_table('sessions')
    op.drop_table('routers')
    op.drop_table('devices')
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_index('ix_commands_router_created')

    op.drop_table('commands')
    op.drop_table('challenges')
    # ### end Alembic commands ###
