http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
    security-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
    redirect-www-to-apex:
      redirectRegex:
        regex: "^https?://www\\.wifikids\\.fun(.*)"
        replacement: "https://wifikids.fun$1"
        permanent: true

  routers:
    www-redirect:
      rule: Host(`www.wifikids.fun`)
      entryPoints: ["web","websecure"]
      middlewares: ["redirect-www-to-apex"]
      service: noop
      tls: {}          # <-- ESSENCIAL para emitir cert de www

  services:
    noop:
      loadBalancer:
        servers:
          - url: http://127.0.0.1
