entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true

providers:
  file:
    filename: /etc/traefik/dynamic.yml
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: cert@wifikids.fun
      storage: /acme/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
