entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true

providers:
  file:
    filename: /etc/traefik/dynamic.yml
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: cert@wifikids.fun          # <-- e-mail fixo e válido
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: web
