name: Deploy WiFi-Kids to Cloudflare Pages

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'ui/webapp/apps/pwa/package-lock.json'

      - name: Install dependencies
        working-directory: ui/webapp/apps/pwa
        run: npm ci

      - name: Run tests
        working-directory: ui/webapp/apps/pwa
        run: npm run test:run

      - name: Build application
        working-directory: ui/webapp/apps/pwa
        run: npm run build
        env:
          VITE_API_URL: ${{ github.ref == 'refs/heads/main' && 'https://api.wifikids.fun' || 'https://staging-api.wifikids.fun' }}
          VITE_MOCK: 'false'
          VITE_DEBUG: ${{ github.ref != 'refs/heads/main' && 'true' || 'false' }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: wifikids-pwa
          directory: ui/webapp/apps/pwa/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  test-backend:
    runs-on: ubuntu-latest
    name: Test Backend API
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run tests
        working-directory: backend
        run: python run_tests.py --coverage --lint --type-check
        env:
          OPENAI_API_KEY: mock_key_for_tests
          AGENT_TYPE: mock